#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and hi for the 9th itiration
i=0
while [ $i -lt 10 ];
do
if [ $i -eq 9 ]
then
echo "Hi"
fi
echo "Holberton School"
let i=i+1
done
