#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times displays bad luck for the 4th loop iteration and displays good luck for the 8th loop iteration
i=0
while [ $i -lt 10 ];
do
if [ $i -eq 3 ]
then
echo "bad luck"
elif [ $i -eq 7 ]
then
echo "good luck"
else
echo "Holberton School"
fi
let i+=1
done
